### ISSUE TITLE
Missing ff and latch groups for cell

### ISSUE THREAD

**Issue by Shatur** [zao111222333/liberty-db#1]
Thanks for this crate!
I trying to migrate to your library from https://github.com/shages/liberty-parse, but noticed that Pin have only `statetable` field. Could you add `ff` and `latch`?

**Comment by zao111222333** [comment]
Sorry for reply late. Sure! I will update and support more attribute those days.

**Comment by zao111222333** [comment]
Hi, it's long time since last update. 
I'm happy to tell you that the current version 0.4.0 support the ff latch group. It was a hard implementation, but finally liberty-db supports `BooleanExpression` and `BDD`, as well as the `ff` and `latch` that we expected!
See more at implementation [src/expression/boolean_expression/latch_ff.rs](https://github.com/zao111222333/liberty-db/blob/v0.4.0/src/expression/boolean_expression/latch_ff.rs) and test function [tests/src/demo.rs](https://github.com/zao111222333/liberty-db/blob/v0.4.0/tests/src/demo.rs#L56)

**Comment by Shatur** [comment]
Thanks! Unfortunately, we switched to our own very simple parser based on pest.
But I'm glad the issue is resolved!
